name: Management Groups

on: workflow_dispatch

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
    # - name: Azure Login action
    #   uses: azure/login@v2
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}
    #     enable-AzPSSession: true

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.9.2'
    
    # - name: Log in to Azure CLI
    #   run: |
    #     az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
    #     az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform Initialization, Validate, Plan, and Apply
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: |
          # Log in to Azure CLI
          az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
          az account set --subscription $ARM_SUBSCRIPTION_ID
          
          cd terraform/modules/managementgroup

          # Initialize Terraform
          terraform init -upgrade

          # Validate the Terraform configuration
          terraform validate

          # Run Terraform Plan
          terraform plan -out=tfplan

          # Apply the Terraform plan
          terraform apply -auto-approve tfplan
