name: LANDING ZONE DEPLOY

on: workflow_dispatch

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
 ame: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
 name: MANAGAMENT GROUP

on: workflow_dispatch

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    
